apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvps-app
  template:
    metadata:
      labels:
        app: dvps-app
    spec:
      containers:
      - name: dvps-app
        image: dvps-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
