apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvps-app

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: dvps-app

  template:
    metadata:
      labels:
        app: dvps-app

    spec:
      containers:
      - name: dvps-app
        image: ujeb2024/dvps-app:latest
        ports:
        - containerPort: 3000

